// This file is auto-generated by createSwiftPackageManager.sh script.
// This file is required by Swift Package Manager for a Swift target.
// It can be empty if the target only serves to wrap other frameworks and resources.
